export const tiles = [
    ////////////////////
    {
        name: "INÍCIO",
        special: true,
        row: 11,
        col: 11,
        bgColor: "#1F",
        color: "#00",
    },
    ////////////////////
    {
        name: "Lion Square",
        color: "#8B4513",
        price: 600,
        rent: 60,
        row: 11,
        col: 10,
        owner_color: "#FF69B4",
    },
    { name: "Cofre", special: true, row: 11, col: 9 },
    {
        name: "Praça da Estação",
        color: "#8B4513",
        price: 600,
        rent: 600,
        row: 11,
        col: 8,
        owner_color: "#FF69B4",
    },
    { name: "Imposto 2", special: true, row: 11, col: 7 },
    { name: "RU", special: true, row: 11, col: 6 },
    {
        name: "China Brasil",
        color: "#87CEEB",
        price: 1000,
        rent: 100,
        row: 11,
        col: 5,
        owner_color: "#FF69B4",
    },
    { name: "Sorte 1", special: true, row: 11, col: 4 },
    { name: "Mac Lanches", color: "#87CEEB", price: 1000, rent: 100, row: 11, col: 3 },
    {
        name: "Q-Pão",
        color: "#87CEEB",
        price: 1200,
        rent: 1200,
        row: 11,
        col: 2,
        owner_color: "#FF69B4",
    },
    ////////////////////
    { name: "CADEIA", special: true, row: 11, col: 1 },
    ////////////////////

    {
        name: "Imperius Fitness",
        color: "#FF69B4",
        price: 1400,
        rent: 1400,
        row: 10,
        col: 1,
        owner_color: "#0069FF",
    },
    { name: "Auditório", special: true, row: 9, col: 1 },
    {
        name: "Zaut Fitness",
        color: "#FF69B4",
        price: 1400,
        rent: 1400,
        row: 8,
        col: 1,
        owner_color: "#0069FF",
    },
    {
        name: "Complexo One",
        color: "#FF69B4",
        price: 1600,
        rent: 1600,
        row: 7,
        col: 1,
        owner_color: "#0069FF",
    },
    {
        name: "Supermercado Pinheiro",
        color: "#FFA50",
        price: 1800,
        rent: 1800,
        row: 6,
        col: 1,
        owner_color: "#0069FF",
    },
    { name: "Sorte 2", special: true, row: 5, col: 1, owner_color: "#0069FF" },
    {
        name: "Supermercado Nosso Atacarejo",
        color: "#FFA50",
        price: 2000,
        rent: 200,
        row: 4,
        col: 1,
        owner_color: "#0069FF",
    },
    { name: "Cofre 2", special: true, row: 3, col: 1 },
    {
        name: "Ginásio Rinaldo Róger",
        color: "#FF00",
        price: 2200,
        rent: 2200,
        row: 2,
        col: 1,
        owner_color: "#0069FF",
    },

    ////////////////////
    { name: "ESTACIONAMENTO", special: true, row: 1, col: 1 },
    ////////////////////

    {
        name: "Pé na aréia",
        color: "#FF00",
        price: 2400,
        rent: 2400,
        row: 1,
        col: 2,
        owner_color: "#0F0",
    },
    { name: "Sorte 3", special: true, row: 1, col: 3 },
    {
        name: "UFC Campus Quixadá",
        color: "#FFD70",
        price: 2600,
        rent: 2600,
        row: 1,
        col: 4,
        owner_color: "#0F0",
    },
    {
        name: "IFCE Quixadá",
        color: "#FFD70",
        price: 2600,
        rent: 2600,
        row: 1,
        col: 5,
        owner_color: "#0F0",
    },
    { name: "Biblioteca", special: true, row: 1, col: 6 },
    {
        name: "UECE Quixadá",
        color: "#FFD70",
        price: 2800,
        rent: 2800,
        row: 1,
        col: 7,
        owner_color: "#0F0",
    },
    { name: "Cofre 3", special: true, row: 1, col: 8 },
    {
        name: "Igreja Matriz",
        color: "#0800",
        price: 3000,
        rent: 300,
        row: 1,
        col: 9,
        owner_color: "#0F0",
    },
    {
        name: "Chalé da Pedra",
        color: "#0800",
        price: 3000,
        rent: 300,
        row: 1,
        col: 10,
        owner_color: "#0F0",
    },

    ////////////////////
    { name: "VÁ PARA CADEIA", special: true, row: 1, col: 11 },
    ////////////////////

    { name: "Mercado Central", color: "#0800", price: 3200, rent: 3200, row: 2, col: 11 },
    {
        name: "Pedra do Cruzeiro",
        color: "#008B",
        price: 3500,
        rent: 3500,
        row: 3,
        col: 11,
        owner_color: "#F00",
    },
    { name: "Sala do CA", special: true, row: 4, col: 11 },
    {
        name: "Pedra da Galinha Choca",
        color: "#008B",
        price: 3500,
        rent: 3500,
        row: 5,
        col: 11,
        owner_color: "#F00",
    },
    { name: "Sorte 4", special: true, row: 6, col: 11 },
    { name: "Imposto", special: true, row: 7, col: 11 },
    {
        name: "Rainha do Sertão",
        color: "#008B",
        price: 4000,
        rent: 400,
        row: 8,
        col: 11,
        owner_color: "#F00",
    },
    { name: "Cofre 4", special: true, row: 9, col: 11 },
    { name: "LUXO", special: true, row: 10, col: 11 },
];